### PR TITLE
Fix for issue #541

### PR DESCRIPTION
**Pull request by lasombra**

### CODE REVIEW

**Comment by gautric** [comment]
thx @lasombra,
I'm just waiting Travis Status, before merge it

**Comment by hekonsek** [comment]
Actually we have to use Rhiot vertx-proton build until Vert.x team starts to release the Snapshot of their work. Added Sosnatype repository to fix #542.

**Comment by lasombra** [comment]
I could not find this artefact or source code anywhere. Where is it?

**Comment by hekonsek** [comment]
Here [1] Ingo. I made this fork to be able to deploy snapshots of the recent vertx-proton works.

[1] https://github.com/rhiot/vertx-proton/tree/initial-work

**Pull request closed without merging**
