### PR TITLE
Create PojosrKuraServer #277

### PR DESCRIPTION
**Pull request by lasombra**

### CODE REVIEW

**Comment by hekonsek** [comment]
Added missing licenses headers. Also excluded Felix Connect from OSGi imports - we don't want to install Felix into OSGi container as it is used only for unit tests.

**Comment by hekonsek** [comment]
Many thanks for the pull request Ingo!

**Comment by hekonsek** [comment]
@lasombra Would you mind creating a documentation for that feature? In `docs/readme.md` file.

**Comment by lasombra** [comment]
@hekonsek Not at all. Gimme a bit of time.

**Comment by hekonsek** [comment]
Thanks in advance! You can add it on the same level as Camel Kura Wifi component documentation. Just after it.

**Comment by lasombra** [comment]
Sure thing.

**Pull request merged**
