### PR TITLE
[closes #318] Create camel-lwm2m component

### LINKED ISSUE #318: Create Leshan Camel client component
I'd like to have Leshan client component which can be used as follows:

    from("timer:deviceHeartBeat").
      to("leshan:myLeshanServer.com:1234/deviceId/com.my.Device");

On the startup of the endpoint client should connect itself to the server. Then LeshanProducer should send new registration request [1] to Leshan server. 

[1] https://github.com/rhiot/rhiot/blob/master/cloudlets/device/default/src/main/groovy/com/github/camellabs/iot/cloudlet/device/client/LeshanClientTemplate.groovy#L82

### PR DESCRIPTION
**Pull request by trohovsky**

### CODE REVIEW

**Comment by gautric** [comment]
thx @trohovsky could you please add RHIOT license header ?

**Comment by trohovsky** [comment]
@gautric license header added to all classes ;-)

**Comment by trohovsky** [comment]
btw. do you have any policy for code formatting and imports ordering? Some profile for IDEA/Eclipse.

**Comment by gautric** [comment]
we use the ASF Camel project convention
we custom our LICENSE header only

**Comment by gautric** [comment]
sorry @trohovsky 

you missed LICENSE header for `log4j.propeties`, `pom.xml` and `lwm2m` files

**Comment by trohovsky** [comment]
license header added

**Comment by hekonsek** [comment]
Hi,

Many thanks for your work! Looks good.

There is one thing that is missing for now. We should be able to specify class of the device enabler, like here [1]. Otherwise we won't be able to call operations on a connected device. So the URI should look like `lwm2m:leshan.eclipse.org:5683:com.example.MyDevice`. The device class might be optional.

Would you be so kind an issue an another pull request that will enable us to specify device class? 

PS Also please note that this is gateway component, so it should be located in `gateway/components` directory. I will move it there.

Cheers!

[1] https://github.com/rhiot/rhiot/blob/712b877d90641f0751a2b666f1b14dfdc32100b4/cloudlets/device/default/src/main/groovy/com/github/camellabs/iot/cloudlet/device/client/LeshanClientTemplate.groovy#L70

**Comment by trohovsky** [comment]
Hi,

true, it should be possible to configure deviceClass. There are other things that can be configured - for example instances of LwM2mInstanceEnabler. Because [ObjectInitializer's API](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/ObjectsInitializer.java) enables configuration of multiple classes/factories by setClassForObject/setFactoryForObject as well as instances of LwM2MInstanceEnabler by setInstancesForObject. All of this is just to provide a list of LwM2mObjectEnabler objects. I suggest to add an option objectEnablersFactory, where the value would contain implementation of ObjectEnablersFactory interface:

```
public interface ObjectEnablerFactory {
    public List<LwM2mObjectEnabler> getObjectEnablers();
}
```

This would make configuration of LeshanClient flexible and lwm2m endpoint URI would stay simple. What do you think?

Cheers,
Tomas

**Comment by hekonsek** [comment]
I would say that we should support both enablers factory and specifying class on the URI level (as this is very popular use case).

What do you think?

**Comment by trohovsky** [comment]
Ok, it makes sense.

**Pull request merged**
