### PR TITLE
212 Gps client coordinates type converter

### PR DESCRIPTION
**Pull request by levackt**

### CODE REVIEW

**Comment by hekonsek** [comment]
Great thanks for the PR!

Can you just add missing license headers to the files? Those are required to get the build passed.

Also, can you add information about this converter to the documentation file?

**Comment by levackt** [comment]
No problem, will resubmit tomorrow and put something in the docs.

**Comment by hekonsek** [comment]
Many thanks Taariq! I really appreciate you contributions to Rhiot!

On Tue, Sep 29, 2015, 19:06 Taariq Levack <notifications@github.com> wrote:

> No problem, will resubmit tomorrow and put something in the docs.
>
> > On 29 Sep 2015, at 18:22, Henryk Konsek <notifications@github.com>
> wrote:
> >
> > Great thanks for the PR!
> >
> > Can you just add missing license headers to the files? Those are
> required to get the build passed.
> >
> > Also, can you add information about this converter to the documentation
> file?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/pull/213#issuecomment-144122996>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by levackt** [comment]
:)

I've fixed the code but looking at the docs I see the problem that brought
us here and it won't be fixed by this PR so lets reconsider and maybe I can
squash it properly.
If we follow the docs like Thomas did, we'll end up with 1 file for every
NMEA line, which is probably not what's expected.

    from("gps-bu353:current-position").
      to("file:///var/gps-coordinates");

In fact that code still won't work because I didn't think it was useful to
convert to an input stream, so the error will persist until you also
convert the body to string, eg
    from("gps-bu353:current-position").
convertBodyTo(String.class).

      to("file:///var/gps-coordinates");

                        convertBodyTo(String.class).

to("file:target/coordinates?fileName=coordinates.txt&fileExist=append").

**Comment by levackt** [comment]
Sorry my browser sent that last message while editing so please open in
github for the full message.

**Comment by hekonsek** [comment]
Actually GPS coordinates per file is something that we usually want, as the single file is a message unit for the File component. So this is fine, especially that you can append to the file, just as you said.

And yes, you have to perform the conversion to String, but this is also something I expected. Otherwise Camel doesn't know if you would like to store the coordinates as text or binary. So this is perfectly fine as well :) .

So all +1 for how it works :)

**Comment by hekonsek** [comment]
Can you update the documentation with the information about the converter and the sample snippet similar to the one you pasted above? I.e.:

    from("gps-bu353:current-position").
         convertBodyTo(String.class).
         to("file:///var/gps-coordinates");

After the documentation update we are good to merge. Thanks!

**Comment by levackt** [comment]
Great, good to know that's how it should work, I thought only of my current
use case.
There were 2 typos in the docs so I piggybacked them, feel free to bounce
the PR if you need it separated.

**Comment by hekonsek** [comment]
Love it. Many thanks for the contribution!

**Pull request merged**
