### PR TITLE
Adding Intel Edison support to rhiot CMD

### PR DESCRIPTION
**Pull request by rimolive**
Please take a look also in a proposed fix I did in https://github.com/rimolive/rhiot/blob/intel-edison-test/tooling/cmd-core/src/main/groovy/io/rhiot/cmd/Cmd.groovy#L52-L56 because even passing --username and --password rhiot CMD was still using the default values ('pi' for username and 'raspberrypi' for password).

### CODE REVIEW

**Comment by hekonsek** [comment]
Hi Ricardo,

I will review your PR after Easter. Sorry for the delay :) .

Cheers!

**Comment by hekonsek** [comment]
@rimolive Can you take a look at those [1] build errors?

[1] https://travis-ci.org/rhiot/rhiot/builds/119273864

**Comment by hekonsek** [comment]
Hi Ricardo, Can you take a look at those failing tests? I can do it if don't have time, just let me know.

**Comment by rimolive** [comment]
I'm facing test errors in openalpr. I'm looking what it is and then fix the cmd tests.

**Comment by rimolive** [comment]
The problem is not the test, but the way the Cmd class is designed. Although having ConsoleInputParser to translate the command-line parameters, the Spring context is initialized without use them. One option I found i use this class: http://docs.spring.io/autorepo/docs/spring-framework/3.2.6.RELEASE/javadoc-api/org/springframework/core/env/JOptCommandLinePropertySource.html but it will need to add spring-framework as dependency to that module. Without it, we can't initialize the context and the beans correctly. Let me know what you think and I can change the code to use this class to parse the command-line parameters.

**Comment by rimolive** [comment]
Please ignore my previous comment. I found a way to do the same without @Value annotations, but still looking for a way to support abbreviations (-u and -pa). It fixes the tests too.

**Comment by hekonsek** [comment]
Merged. Many thanks!

**Pull request merged**
