### PR TITLE
Detect RPI from Mac on en0

### PR DESCRIPTION
**Pull request by levackt**
RpiDetectorTest doesn’t run with a connected PI on the wifi when the laptop uses en0, if this is something I can configure differently please advise.
RpiDetectorTest executes and passes after this change.

**- org.junit.AssumptionViolatedException: The test should be executed only when the proper network interfaces are available.**

Network setup shows the following;
**networksetup -listallhardwareports**
SNIP
Hardware Port: Wi-Fi
Device: **en0**

### CODE REVIEW

**Comment by levackt** [comment]
Whoops, back to the drawing board, still not detecting my pi and en0 is useless unless I'm emulating the pi which isn't too useful anyway.

**Comment by hekonsek** [comment]
Hi Taariq,

Good point. I have added [1] the assumption to the test so it won't be executed if Raspberry Pi is connected to the local network.

BTW Would you be so kind and create the new pull request so we could support Mac's `en` interface? I would highly appreciate that.

Cheers!

[1] https://github.com/rhiot/rhiot/commit/72a124a05f2c613998cbac5d6207d141489eda44

**Comment by levackt** [comment]
Great, I got mine working this morning and I'm able to ssh the app and run it on the PI

**Comment by hekonsek** [comment]
Can you clean up this pull request or create the new one? I see 5 files changed, while only one change is needed. Many Thanks!

**Comment by levackt** [comment]
No problem, will resubmit tomorrow with a new ticket for the other changes.
I also need to see why I'm getting 2 devices when only one should be detected.

**Comment by hekonsek** [comment]
That would be great! Current code works fine for my Ubuntu OS, but it would be cool to have the code verified against two setups :) . Looking forward to seeing the PR!

**Pull request closed without merging**
